### ISSUE TITLE
Bring language support to 100% for partially covered languages

### ISSUE THREAD

**Issue by davelab6** [jpt/barlow#14]
I'd like to request just a few languages which have over 90% character support and are just missing a few characters according to Unicode CLDR :)

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| Romanian (ro) | 101/102 | 99 | \u2010 (‐) |
| Estonian (et) | 104/105 | 99 | \u014f (ŏ) |
| French (fr) | 111/113 | 98 | \u2010 (‐), \u01d4 (ǔ) |
| Indonesian (id) | 73/74 | 98 | \u2010 (‐) |
| Serbian (Latin) (sr-Latn) | 83/84 | 98 | \u2010 (‐) |
| Dutch (nl) | 107/110 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Polish (pl) | 123/126 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Latvian (lv) | 106/109 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Swedish (sv) | 106/109 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Afrikaans (af) | 105/108 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Icelandic (is) | 100/103 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| German (de) | 121/126 | 96 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u014f (ŏ), \u016d (ŭ) |
| Czech (cs) | 125/130 | 96 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u014f (ŏ), \u016d (ŭ) |
| Danish (da) | 106/110 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″), \u01ff (ǿ) |
| Filipino (fil) | 94/97 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Croatian (hr) | 86/89 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Lithuanian (lt) | 102/106 | 96 | \u2010 (‐), \u0129 (ĩ), \u0169 (ũ), \u1ebd (ẽ) |
| Slovak (sk) | 126/131 | 96 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u014f (ŏ), \u016d (ŭ) |
| Slovenian (sl) | 108/112 | 96 | \u0115 (ĕ), \u012d (ĭ), \u014f (ŏ), \u016d (ŭ) |
| Malay (ms) | 80/83 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Albanian (sq) | 84/87 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Finnish (fi) | 154/162 | 95 | \u2010 (‐), \u021f (ȟ), \u015d (ŝ), \u0292 (ʒ), \u01e5 (ǥ), \u01e7 (ǧ), \u01e9 (ǩ), \u01ef (ǯ) |
| English (en) | 114/121 | 94 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u014f (ŏ), \u016d (ŭ) |
| English (United Kingdom) (en-GB) | 114/121 | 94 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u014f (ŏ), \u016d (ŭ) |
| Spanish (es) | 123/130 | 94 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u014f (ŏ), \u016d (ŭ) |
| Spanish (Latin America) (es-419) | 123/130 | 94 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u014f (ŏ), \u016d (ŭ) |
| Portuguese (pt) | 117/124 | 94 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u014f (ŏ), \u016d (ŭ) |
| Turkish (tr) | 123/130 | 94 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u014f (ŏ), \u016d (ŭ) |
| Hungarian (hu) | 126/133 | 94 | \u0115 (ĕ), \u012d (ĭ), \u014f (ŏ), \u2052 (⁒), \u016d (ŭ), \u27e8 (⟨), \u27e9 (⟩) |
| Portuguese (Portugal) (pt-PT) | 117/124 | 94 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u014f (ŏ), \u016d (ŭ) |
| Azerbaijani (az) | 92/97 | 94 | \u2010 (‐), \u2032 (′), \u2033 (″), \u0259 (ə), \u018f (Ə) |
| Uzbek (uz) | 82/87 | 94 | \u2010 (‐), \u2032 (′), \u2033 (″), \u02bb (ʻ), \u02bc (ʼ) |
| Catalan (ca) | 121/129 | 93 | \u2010 (‐), \u0115 (ĕ), \u012d (ĭ), \u2032 (′), \u2033 (″), \u0140 (ŀ), \u014f (ŏ), \u016d (ŭ) |

**Comment by cdlm** [comment]
Esperanto (eo) needs just a dozen latin letters with diacritics: ĉĈĝĜĥĤĵĴŝŜŭŬ (that's cC gG hH jJ sS with circumflex, and uU with breve).

**Comment by thlinard** [comment]
I believe the title is misleading: 100% compatibility with CLDR can be see as a desirable goal, but the coverage requested isn't necessary for full support of the designated languages.
French doesn't need ǔ, English doesn't need ĕĭŏŭ, etc.: this is because CLDR requests romanization, and specially pinyin romanization.

**Comment by jpt** [comment]
All done -- not in binaries yet because need to figure out what I'm doing with ascender height for #15
