### ISSUE TITLE
Please fix the kerning with polish "ł" character

### ISSUE THREAD

**Issue by narvego** [jpt/barlow#17]
Hello,

This font is great. Clear and professional. And beauty. But, I have found an one big problem with kerning polish "ł" character with some other letters. I have send you an screenshots. It seems, that there is only need to increase a space after and before polish "ł", when this letter appears in pair with most of next characters.

Also, after polish "ą" there is little too big space. But it is not a big problem.

Can you fix this "ł" error? I will be a very thankful! :)

Screen with errors:
![barlow-kerning](https://user-images.githubusercontent.com/33578072/32691611-b8fb6756-c70a-11e7-8907-7eda85bf1694.png)

![barlow-kerning2](https://user-images.githubusercontent.com/33578072/32691692-d31fb898-c70b-11e7-9bc4-5c26e8d1be39.png)

**Comment by jpt** [comment]
Hi @narvego - thank you for opening this issue, I really appreciate the help from readers of non-English languages! I will make sure a fix for both the ł and ą is included in the next release, which should be fairly soon as I've noticed another unrelated but easy-to-fix spacing issue with the black weight. 

Aside from the spacing issue, do you think the Polish characters mostly look correct?

Thanks again.

**Comment by jpt** [comment]
@narvego This is fixed as of commit d50bfaa -- please let me know if you find other problems with Polish support, cheers!

**Comment by narvego** [comment]
Hello,

I have found a small problem. Kerning of "Ł" letter with letters placed on left side of "Ł", like "M", "N", "B", "C", "D", "S", "U" and many others, in medium, semibold and other weights is not correctly, as we can see on the picture:

This happens in Barlow, Barlow Condensed and Barlow Semicondensed family.

![barlow-kerning6](https://user-images.githubusercontent.com/33578072/33190301-8f7df0f6-d0ab-11e7-8cc5-66f9f1be0dae.png)

**Comment by jpt** [comment]
Hi @narvego - thanks again for the help! I'm glad you're enjoying the font enough to want to improve it :)

I'll add this to 1.203, which should be ready in a few days. I will close this issue when I've taken care of it.

**Comment by jpt** [comment]
Ok @narvego - should be fixed in 1.203. Thanks again for the bug report!

**Comment by powie3** [comment]
This "ł" is just designed badly (nothing personal).
![image](https://github.com/jpt/barlow/assets/154506593/052e6c07-a8da-4075-99d5-d7c52c017ed0)
With this mechanically done diagonal stroke (looking as an adhesive plaster) the kerning is really hard to perform correctly.

**Comment by jpt** [comment]
@powie3 I agree with you there are a number of Latin characters I am making changes to for the next release. No timeline yet but feel free to open a new issue if you want to keep track
