### ISSUE TITLE
Problem with italic "p"

### ISSUE THREAD

**Issue by narvego** [jpt/barlow#19]
Hi,

There is a small problem with italic "p". Not only in Barlow Condensed - SemiBold Italic, but in other faces too.  Just look please:

![barlow-kerning4](https://user-images.githubusercontent.com/33578072/32835498-9ddfdffc-ca06-11e7-9047-00f850d63a37.png)

Ps.
It is "barlow-1.104" version and "ttf" files. In "otf" files this problem seems to not exist.

**Comment by jpt** [comment]
Hi @narvego -- thanks for noticing this, I'm looking into it! I think it's an issue with the way Glyphsapp is handing the decomposition of Glyphs when exporting TTF files, but not sure yet...

**Comment by jpt** [comment]
I've alerted the Glyphs team to the issue that caused this -- https://forum.glyphsapp.com/t/decompose-glyphs-before-transformations/5497/10

And have recompiled the binaries using Glyphs 2.5b-1084 which appears to fix the problem. Will push up a new release (1.105) then close this issue.
