### ISSUE TITLE
Improve Ø and ø (oslash) angles

### ISSUE THREAD

**Issue by jpt** [jpt/barlow#21]
I did a fairly poor job of drawing these Glyphs

<img width="277" alt="screen shot 2017-11-18 at 7 24 40 pm" src="https://user-images.githubusercontent.com/5319916/32987113-4fdfe7b0-cc96-11e7-8a60-342562f3d642.png">

<img width="357" alt="screen shot 2017-11-18 at 7 24 20 pm" src="https://user-images.githubusercontent.com/5319916/32987114-4ff7d0d2-cc96-11e7-8546-da429b12d57f.png">

Would probably be an improvement for the Bold thru Black weights if it looked more like the currency symbol with only one slash e.g.

<img width="114" alt="screen shot 2017-11-18 at 7 27 18 pm" src="https://user-images.githubusercontent.com/5319916/32987132-9a101274-cc96-11e7-86c5-534abaf63a75.png">

Need to figure out if it's possible to have contextual alternates in variable fonts, so if the weight axis is > 700 (or whatever), it switches out

**Comment by davelab6** [comment]
It is possible

**Comment by jpt** [comment]
In Glyphsapp it's not possible for all glyphs that have brace layers because bracket + brace layers cant be combined and bracket layers cant be used in multi axis fonts

But because it's an /oslash, I can luckily get away with a trick :)

https://forum.glyphsapp.com/t/bracket-layers-in-variable-fonts-bracket-brace/7655/4

**Comment by Maggern** [comment]
Question: Did commit a2b7581 change the Ø in the bolder versions so that there is no line through the character?
