### ISSUE TITLE
Weird "c" letter in Semibold, Bold and Black weights

### ISSUE THREAD

**Issue by pietrogregorini** [jpt/barlow#25]
Hey there, I just found out this issue zooming on Illustrator. Look at the weird angle in bottom left circle of the letter. I left the medium weight on the right as a reference (it doesn't show up from lighter weights up to Medium).

![schermata 2017-12-19 alle 10 35 10](https://user-images.githubusercontent.com/3169323/34150746-8e4bb166-e4a9-11e7-8531-35e8200c9948.png)

**Comment by jpt** [comment]
Hi @pietrogregorini - thanks for reporting the issue, I'm having trouble reproducing it. Can you tell me where you got the font from (Google Fonts, Github), what version it is (Get Info) and which font file it is?

**Comment by jpt** [comment]
This is what I'm seeing on OSX with a TTF file, v 1.208 downloaded from Github, using Barlow Semibold

<img width="831" alt="screen shot 2017-12-19 at 2 06 50 am" src="https://user-images.githubusercontent.com/5319916/34151802-5afe6814-e461-11e7-8f9e-08fcd76962ec.png">

**Comment by pietrogregorini** [comment]
Hi @jpt  !
Yeah, sure. I downloaded today from Google Fonts, version is 1.101, used on Illustrator 22.0.1 on a macOS 10.13.2. By the way, you have to **zoom in at 600%** to start seeing it.

**Comment by jpt** [comment]
Thanks @pietrogregorini  -- I suspect this is an issue that was already resolved but isn't yet updated on Google. Can you download the latest version (v1.208) from https://github.com/jpt/barlow/archive/master.zip (inside the fonts directory) and let me know if you still have the problem? If that fixes it, I will alert Google and keep this issue opened until it's updated there.

**Comment by pietrogregorini** [comment]
You're welcome @jpt !
Yep, the issue is resolved with last version 1.208, both TTFs and OTFs – though OTFs doesn't group fonts such as in TTFs version,so I had all the weights split instead of having them grouped under one name, whatever.

Thank you so much! Just remember to notify Google folks to update to the last version ;)
