### ISSUE TITLE
Character width – ď – 0x010F

### ISSUE THREAD

**Issue by tomaskavalek** [jpt/barlow#30]
There is very big space between character „ď“ and other characters. It should be less – glyph width 423 for example, in my case. Final width is on you ;-)

See attachments. Please, repair it for a better glyph width.

![doura](https://user-images.githubusercontent.com/210119/36091968-f966b3da-0fe5-11e8-9fcb-a191f2525270.png)

**Comment by jpt** [comment]
Hi @tomaskavalek - thanks for opening this issue! I'll work on a fix and let you know when it's in

**Comment by jpt** [comment]
Hi @tomaskavalek  this should be fixed now! Thanks again for reporting the issue.

**Comment by tomaskavalek** [comment]
Good job. Thanks.
