### ISSUE TITLE
Wrong caron type in U+0165 (LATIN SMALL LETTER T WITH CARON)

### ISSUE THREAD

**Issue by danhelekal** [jpt/barlow#32]
The ť glyph (U+0165) uses a wrong caron symbol. You already have the correct caron that should be used in the ď glyph (U+010F). 

Applies only to lowercase ť, not to uppercase Ť.

**Comment by jpt** [comment]
Hi @danhelekal  -- thanks for opening the issue! I am going to work this into an already-upcoming incremental release (1.401). I'll tag you when it's done -- thanks again for bringing this to my attention!
