### ISSUE TITLE
Barlow lower case 'c' issue

### ISSUE THREAD

**Issue by jackmez** [jpt/barlow#33]
There seems to be an issue with the lower case 'c' on certain weights when used with the Adobe Suite. 

See the screenshots below for the 'c' used in Illustrator and Sketch with Barlow Semibold.
The 'c' in Illustrator appears to have an extra point along the bottom curve.

Adobe Illustrator cc 22.0.1
<img width="1194" alt="screenshot 2018-04-09 14 40 13" src="https://user-images.githubusercontent.com/18393982/38501147-33bcef0a-3c04-11e8-9297-f8b3edfce74d.png">

Sketch 49.3
<img width="1098" alt="screenshot 2018-04-09 14 41 18" src="https://user-images.githubusercontent.com/18393982/38501145-3377fad0-3c04-11e8-808a-3c564cf8be19.png">

**Comment by jpt** [comment]
Hi @jackmez -- thanks for reporting the issue. Is this the OTF or TTF file, and where did you obtain it (Github, Google Fonts, etc)?

**Comment by jackmez** [comment]
It was obtained from Google Fonts.
Thanks

**Comment by jpt** [comment]
Hi @jackmez -- interesting, I wonder if this is an issue with the Google Fonts API. Can you download the font from https://github.com/jpt/barlow/archive/master.zip or https://tribby.com/fonts/barlow/download/barlow-1.403.zip and let me know if the issue persists?

**Comment by jpt** [comment]
Hi @jackmez -- closing this issue due to non-response, but please let me know if you still have problems with v1.4!

**Comment by rhondacrim** [comment]
Hi. I had the same issue with the semi-bold - black "c" downloaded from Google Fonts. The fonts downloaded from the links above do not contain that error, but still have a small glitch in the "c". Please see screenshots. Thank you!

![image](https://user-images.githubusercontent.com/14790523/45781193-55924680-bc2d-11e8-99bf-d4e68253d584.png)

**Comment by rhondacrim** [comment]
![image](https://user-images.githubusercontent.com/14790523/45781302-938f6a80-bc2d-11e8-8203-21e8de68b8bf.png)
