### ISSUE TITLE
Wrong caron on ľ (U+013E) and Ľ (U+013D)

### ISSUE THREAD

**Issue by MichalRemis** [jpt/barlow#34]
The ľ glyph (U+013E) and also upper case Ľ (U+013D) uses a wrong caron symbol. You already have the correct caron that should be used in the ď glyph (U+010F).

Also thank you for good work and great font.

**Comment by jpt** [comment]
Hi @MichalRemis - thanks for opening the issue, I will work on a fix and let you know when it's available.

**Comment by williamflaherty** [comment]
@jpt Similarly, the ť glyph (U+0165) displays the incorrect caron. Thanks!

**Comment by MichalRemis** [comment]
@williamflaherty I think ť is already fixed if you download Barlow font from github. Problem is only with Google Fonts - they need to update.

**Comment by williamflaherty** [comment]
@MichalRemis ah I was using the Google font, and that's why I missed it, that was helpful, thanks!
