### ISSUE TITLE
Superscript zero U2070 is missing

### ISSUE THREAD

**Issue by maasj** [jpt/barlow#44]
It seems like the glyph for unicode Superscript Zero, U2070, is missing.  At least on the Semi Condensed fonts.  All the other unicode superscript numbers are present.  Was the zero skipped on purpose or was that an oversight?

The missing superscript zero is causing me some headaches so unless there's a good reason not to add it I'd love to see it get added.

Thanks for your hard work!

**Comment by jpt** [comment]
Hi @maasj -- thanks for opening the issue, this is definitely a bug and not intentional. Can you let me know which version of the font you're using and where you obtained it from? I'll take a look.

**Comment by maasj** [comment]
You're welcome.  Thanks for the quick confirmation that it's a real bug.

I'm seeing the problem using the OTF files from your GitHub project, such as:

https://github.com/jpt/barlow/blob/master/fonts/otf/BarlowSemiCondensed-Regular.otf
https://github.com/jpt/barlow/blob/master/fonts/otf/Barlow-Regular.otf

Is that what you're looking for?

**Comment by maasj** [comment]
I know you're a volunteer and I'm so grateful that you've made this font and shared it with the world.  So I don't mean to pester, but do you have any guess as to when you might be able to fix this bug?

**Comment by jpt** [comment]
Hi @maasj - thanks for the help on this issue! Somewhere around a month, likely sooner. There have been a few issue raised recently and if I'm going to do a new release I'd like to get a few of them fixed at the same time. I appreciate your patience, thank you again for bringing the issue to my attention.

**Comment by maasj** [comment]
Awesome, thank you!

**Comment by jpt** [comment]
Hi @maasj, this is fixed i [version 1.422, which you can download here](https://github.com/jpt/barlow/archive/master.zip) (you'll find the files in the `fonts` folder). If there is still a problem (or if I've introduced any new ones 🙂) let me know and I'll re-open the issue.  Thanks again for the help!

**Comment by maasj** [comment]
I just tested it out and I can confirm that there's now a character for the unicode Superscript Zero.  Hooray!  However, it looks to me like the superscript zero isn't vertically aligned with the other unicode superscript numbers 1-9.  The new superscript zero is being placed a little lower than the other superscript numbers.  I'll attach a screenshot of what I'm seeing in Apple Pages 8.1 on macOS.  I'm also seeing the same behavior in another app I use.

![barlow_superscript_zero_vertical_alignment](https://user-images.githubusercontent.com/137552/60683937-c6c38300-9e68-11e9-9c85-2f38609b5c5a.png)

**Comment by jpt** [comment]
hi @maasj -- just pushed out a new fix -- can toy let me know if it's working as intended? Thanks!

**Comment by maasj** [comment]
Nailed it!  Thank you!!!
