### ISSUE TITLE
markup U00B7 in MS Word on Windows PCs

### ISSUE THREAD

**Issue by fbim-genosr** [jpt/barlow#45]
Hi all,

on Windows PCs we recognized a strange behaviour with barlow. When you turn on MS-Words "show markup" function, in Barlow a space shows a "." glyph instead of a floating point. This makes it really hard to differ spaces from full stops.

I think it is U00B7.

cheers
Sebastian

**Comment by jpt** [comment]
Hi @fbim-genosr Sorry for the late reply, I missed this one. I'm looking into the issue. There are a couple of other Windows compatibility issues that I am aware of, and I'll likely roll out of fix with all of them at the same time. Thanks for opening the issue.

**Comment by agusmba** [comment]
FWIW, with Barlow 1.4.0.8 I don't see this issue on my Windows7 (Word 2013 or 2016):

![image](https://user-images.githubusercontent.com/3104020/62351826-efda4080-b506-11e9-873d-9c0baebc1cc7.png)

**Comment by jpt** [comment]
hmm I also haven't been able to reproduce, unfortunately. my recommendation is to try the latest binaries: https://github.com/jpt/barlow/tree/1.5/fonts in the 1.5 branch. will reopen if I hear back that there are still issues. thanks!
