### ISSUE TITLE
Parentheses next to each other are difficult to read

### ISSUE THREAD

**Issue by macalinao** [jpt/barlow#48]
![Screenshot_2019-04-04_15-51-43](https://user-images.githubusercontent.com/401263/55593680-9c3f1e00-56f1-11e9-9a14-ff7af2381979.png)

Example attached. Is there a way we can add spacing between ")("s?

**Comment by jpt** [comment]
@macalinao thanks for opening the issue. I agree. In fact, the entire font is currently being re-spaced and re-kerned. I would guess I'll be able to roll out a fix around end-of-month. This issue is a priority, and I'll update you when the fix is in.

**Comment by macalinao** [comment]
Thank you!

**Comment by jpt** [comment]
Hi @macalinao sorry for the delay on this one -- can you check the latest [version 1.422, which you can download here](https://github.com/jpt/barlow/archive/master.zip) (you'll find the files in the `fonts` folder). Spacing and kerning should be much-improved overall. I'm going to go ahead and close the issue, but if there's still a problem, let me know and I'll open it back up.

**Comment by rfischmann** [comment]
Sorry for re-opening this old ticket, but we've just adopted Barlow as our site's main font and the parenthesis' kerning is bothering us a lot.

Here's a simple example of how it looks, from Google Fonts: https://d.pr/i/JVTSwQ

It doesn't look there's a space before the opening parenthesis at all.

Any way to make this better? Thanks.

**Comment by sophiebits-humu** [comment]
@rfischmann Google Fonts is using an old version of Barlow.
