### ISSUE TITLE
Legibility problem in heavy weights of lowercase "i"s and other details

### ISSUE THREAD

**Issue by neagle** [jpt/barlow#50]
We use Barlow for our admin interface at my company, and we've been having problems with the legibility of the lowercase i at 14px, semi-bold weight -- it's blurry enough to look like a lowercase l (L). (Note: this is not a problem on retina displays, or other high-pixel-density screens.)

In investigating this problem, I was surprised to find that [Google font's specimen page for Barlow](https://fonts.google.com/specimen/Barlow) does *not* have the same problem. At the same size and weight, the i's details are crisp and distinct, as are certain features of other glyphs, like the top of lowercase "f"s.

After running through all the CSS styles on the text in an attempt to figure out what Google fonts might be doing, I finally tried grabbing the font _file_ that their specimen page uses directly... and I found that I was able to get the crisp version myself. You can see a comparison of the two [on this CodePen](https://codepen.io/neagle/pen/rbwPPd). And, in case you don't have a screen that produces the same differences, here's a screenshot:

![Screen Shot 2019-04-15 at 9 54 55 AM](https://user-images.githubusercontent.com/176993/56138279-956fa100-5f64-11e9-9ed8-b53324d1ff46.png)

I downloaded the official version of Barlow from this repo and double-checked against the `.woff2` versions of the files, just to make sure, and I got the same blurry rendering displayed shown above in the lower example.

For the moment, I've plucked these mysterious versions from the Google fonts specimen page and am using them, which solves my problem, but I'd love to solve the mystery. I'm not a typeface expert, so I don't know if there's a possibility there was some kind of regression involving hinting (?) or something else at some stage in Barlow's development and that Google Fonts has an older version of the file for their specimen page.

Here's an example of how the new version of the files I grabbed changed our admin interface:

**BEFORE:**

![Screen Shot 2019-04-12 at 2 56 28 PM](https://user-images.githubusercontent.com/176993/56138615-3d856a00-5f65-11e9-9798-c76e93cab8f9.png)

**AFTER:**

![Screen Shot 2019-04-12 at 2 56 07 PM](https://user-images.githubusercontent.com/176993/56138627-437b4b00-5f65-11e9-9a51-614383f02913.png)

I was hoping someone here might be able to shed some light on the problem. I thought it might be significant for Barlow's use, too, since this has a fairly major effect on Barlow's appearance on many screens at fairly normal size and weight. Thank you!

**Comment by jpt** [comment]
Hi @neagle -- thanks for opening the issue. I wonder if hinting got missed in the most recent commit fixing a metadata issue with Ø, and maybe the Google specimen is actually running an earlier version? Not sure --  I will take a look and get back to you as soon as I've discovered the underlying issue.  cc @davelab6 in case you can shed some light on the GF "looks fine in specimen but not provided CSS" thing.

**Comment by neagle** [comment]
That could certainly explain it. Thanks for looking into the problem, @jpt!

**Comment by jpt** [comment]
Hi @neagle -- sorry to follow up so late, but this [is fixed in the latest version](https://github.com/jpt/barlow/archive/master.zip). I'm closing the issue, but feel free to re-open if you have different results!

**Comment by neagle** [comment]
Excellent: no problem on the time, we were able to grab an old version to use in the interim. It'll be great to update with the official version. Thanks a lot!
