### ISSUE TITLE
Rendering issue on Ubuntu & Windows with Self-Hosted Fonts

### ISSUE THREAD

**Issue by thatcort** [jpt/barlow#53]
I tried self-hosting font files and ran into rendering issues on Windows and Ubuntu that I don't see when using Google Fonts. It looks fine on Mac in both cases.

On Ubuntu and Windows the baseline of the characters is inconsistent, leading to lines with some characters higher than others. Note that this is using the files from a git pull of tag 1.422.

An image showing the problem and the css used to load the font are attached.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/12662578/61654684-f8bb4e80-ac8a-11e9-83b1-6ed7687b2673.png">

[barlow.css.txt](https://github.com/jpt/barlow/files/3418702/barlow.css.txt)

**Comment by jpt** [comment]
Hi @thatcort -- thanks for reporting the issue. I can only guess that there's an issue with the hinting in this release; I'll take a look at it and get back to you.

**Comment by jpt** [comment]
Hi again @thatcort -- can you test these new WOFF2 files and let me know how they work? Thanks!
[woff2-new.zip](https://github.com/jpt/barlow/files/3424428/woff2-new.zip)

**Comment by thatcort** [comment]
This seems much better - thanks!

**Comment by aristid** [comment]
There is still a rendering issue on Windows 10, at least for Barlow Bold:
![barlow-bold-problem](https://user-images.githubusercontent.com/8337421/100399860-ae06cf00-3054-11eb-8a9c-dc1302929169.png)
I'm using woff2, it looks the same in Chrome and Firefox.
Thank you!

**Comment by chiangs** [comment]
Self hosting on webapp viewed in Windows 11 Chrome. If I wrap it in a `<h123456/>` element the zero is fine, but in `<p/>` it shows the uneven height for the zero.
![image](https://user-images.githubusercontent.com/10984593/218543693-b1b30ca6-7f87-4829-b068-58d295d6bc24.png)
