### ISSUE TITLE
Windows (Office), too much weight difference between Bold and Regular

### ISSUE THREAD

**Issue by agusmba** [jpt/barlow#54]
First of all thank you for this wonderful font and all its many weights and variants.

I've been using it recently in some Office documents, but due to how windows selects fonts when using "Bold" text in Powerpoint or Word, the results are a bit too heavy. I know that it is also a question of personal aesthetics but please see the example below:

![image](https://user-images.githubusercontent.com/3104020/62354736-d688c280-b50d-11e9-9110-372e6ed84ae0.png)

The first line is using `Barlow` (weight 400) and the last part is using Word's Bold option. It seems to be selecting the `Barlow Bold` font (weight 700)

For comparison's sake, the second line is using `Barlow Medium` (weight 500) and when using Word's Bold option, Word interpolates a weight that seems to have quite lighter contrast.

In the third line I have manually selected alternative fonts to arrive at a more pleasing result (for me): `Barlow` with `Barlow SemiBold` (weight 600) instead of using Word's Bold option.

I'm not sure what an elegant solution would be. As an example, I edited the metadata of `Barlow Semi Condensed` and changed its family to `Barlow Semi Condensed Standard` thus preventing Word from automatically selecting `Barlow Semi Condensed Bold`. You can see the difference below. In the first line I use the official `Barlow Semi Condensed` and the second line uses the one with the modified metadata:

![image](https://user-images.githubusercontent.com/3104020/62355786-0042e900-b510-11e9-8233-f1e40edcdbe2.png)

As you can see the interpolated option in the second line looks better (again IMHO)

**Comment by jpt** [comment]
Hi @agusmba -- thank you for the detailed issue and thoughtful suggestions. 

First, can you make sure you're using the latest Barlow version (v1.422)? I believe that prior to this release, Barlow was missing the Windows-specific `WWSFamilyName` and `WWSSubfamilyName` metadata, which could be causing the issue.

If that doesn't fix it, there are a couple of other possibilities: Glyphs.app has a "Style Linking" feature that I don't believe Barlow is taking full advantage of. It's also possible that Barlow will need some additional `styleMapFamilyName` metadata.

The third possibility is that MS Office is simply doing something weird and applying a faux bold that is beyond the control of the font's metadata, in which case there won't be much I can do.

In any event, I agree with you; this is more "bug" and less "aesthetic preference," IMO. 

I'll look into it and update the issue as I learn more. I can't give an ETA, and it may take some time, but this is certainly on my radar now.

Thanks again.

**Comment by agusmba** [comment]
Hi @jpt -- thank you for your quick answer!
I tried with the latest release, and apart from some confusion with Windows' Font view (light, extralight and thin are shown there with the same name :man_shrugging: ) the behavior in Word is the same as I reported.

I understand this is a complex issue and I'm just glad you agree with my report and will keep this on your radar. Thank you!

**Comment by agusmba** [comment]
Just to clarify I'm using the TTF fonts (it seems Barlow's OTF variants are not bold-interpolated correctly by Word)

**Comment by agusmba** [comment]
I think the reason I opened this issue was a personal preference for *lighter* bolds, which might go against widespread aesthetic conventions, so maybe there is no real problem here (probably due to years of experiencing Word's lighter *faux bold*).

MS Word is automatically selecting the bold variant (700 weight) of the regular font (400 weight) as specified in the font.
This is currently the only Style Linking configured (combination of Font Family Name and Font Subfamily Name) that includes the bold variants. All other Style Linking only include regular and italic, so Word will use *faux bold* for the rest of the variants (Thin, ExtraLight, Medium, SemiBold, ExtraBold, Black).

**Comment by jpt** [comment]
Ah, I understand. Thank you for clarifying. I'll close this as an issue, though I'll consider it. This may ultimately be the difference between a display style and text style..
