### ISSUE TITLE
Missing UNICODE characters

### ISSUE THREAD

**Issue by tue0506** [jpt/barlow#56]
Can you add UNICODE support for Barlow font? I'm using your font on an Android device (as default system font) and some UNICODE characters are missed. Please look into it :) Thank you so much for this great font!

**Comment by fitojb** [comment]
> Can you add UNICODE support for Barlow font?

The font is Unicode-compliant already. Unicode is an encoding standard, and “adding Unicode support” does _not_ entail adding every single character in it.

> **some** UNICODE characters are missed

When filing issues, _puhlease [be specific](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)_; be a good open-source citizen. Nobody can read minds here; I for one can’t tell which are the characters that you are missing. (Also, bear in mind that a OS system font may contain Private Use Area (PUA) characters specific to it, that aren’t appropriate for replicating in other fonts.)

**Comment by jpt** [comment]
Hi @tue0506 -- can you take a screenshot of the problem you're having? It may be related to the PUA characters @fitojb is referring to, but I'd like to be sure. Thanks!

**Comment by tue0506** [comment]
The first pic is Roboto font. The second one is Barlow.
![Screenshot_2019-09-10-11-36-08-454_com darkorbitstudio fontviewer](https://user-images.githubusercontent.com/31882623/64584607-a4496b00-d3bf-11e9-8558-6d3902725be9.jpg) 
![Screenshot_2019-09-10-11-36-33-416_com darkorbitstudio fontviewer](https://user-images.githubusercontent.com/31882623/64584616-b0cdc380-d3bf-11e9-9b8e-968314b71f24.jpg) 
![Screenshot_2019-09-10-11-34-30-531_org thunderdog challegram](https://user-images.githubusercontent.com/31882623/64584628-b75c3b00-d3bf-11e9-9de0-e3099adad9fa.jpg)
![Screenshot_2019-09-10-11-33-57-519_org thunderdog challegram](https://user-images.githubusercontent.com/31882623/64584629-b7f4d180-d3bf-11e9-94bb-4039de2a2479.jpg)

**Comment by jpt** [comment]
Thanks @tue0506 -- it looks like [Unicode Small Caps](https://en.wikipedia.org/wiki/Small_caps#Unicode) are the feature you want? I can add this to the list of things to implement in Barlow, but I can't say when I'll have a chance to get to it. Thanks for the suggestion.

**Comment by jpt** [comment]
To be honest, I can't tell exactly which characters those are; some look like homoglyphs/[faux cyrillic](https://en.wikipedia.org/wiki/Faux_Cyrillic)? Could you paste the text here? (The text that you took the screen shot of)

**Comment by tue0506** [comment]
I can't paste all characters here because I don't know how to find those special characters. But I have an idea: some Android devs/designers use Roboto font as a base, and implement Roboto's special characters to the font which is missing those characters (because Roboto has all characters). 
Hope it will help you :)

**Comment by geoffreycrofte** [comment]
More generally, don't implement these character because screen readers can't deal with those glyphs properly.
Better display not supported characters so content editors stop making shitty content :)
Sorry not sorry @tue0506 :p 

An example of the complexity behind my message: 
https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/

**Comment by jpt** [comment]
I will not be implementing this.
