### ISSUE TITLE
Add smallcaps -- possible with VF?

### ISSUE THREAD

**Issue by jpt** [jpt/barlow#6]
Not sure how to define arbitrary axes in Glyphs but would be cool if the smallcaps could be part of the GX file (or whatever ends up winning on the web)

**Comment by davelab6** [comment]
I suggest posting about that in type drawers because I had just heard this
suggestion from @twardoch and would be great to hear a fresh voice of a
real type designer

**Comment by jpt** [comment]
Started a thread if you haven't seen it -- http://typedrawers.com/discussion/2081/small-caps-as-a-variable-font-axis-in-glyphs -- sounds impossible in the way I intended, but seems like there's interest for something like "smart components for VF"

**Comment by jpt** [comment]
Smallcaps are in but not using any VF stuff. Closing until there's support.
