### ISSUE TITLE
Is this font still in development?

### ISSUE THREAD

**Issue by evolbug** [jpt/barlow#92]
Hey, I really like the font, but it appears there have been no changes for 2 years now.

Version 1.4 has very minor rendering issues in some situations, so I was looking if there was any update.

It seems like there's a bunch of fixes in 1.5 according to issues here, but most of the font files in that branch appear to be incomplete as they don't render correctly apart from a few ttf ones.

Are there plans to release 1.5 sometime in the future?

**Comment by jpt** [comment]
hi @evolbug - that is a reasonable question. short answer is yes. long answer is that this is a volunteer effort with one contributor who has been ill for most of the year, and pull requests are welcome. I will get in touch with google fonts to get a better idea of how much QA and design review will be necessary for 1.5 as that is the biggest unknown in terms of when the release may come around.

**Comment by evolbug** [comment]
No worries, completely understand that this is a one man effort and hope you get better soon!

I was mostly just checking in for myself and others who like the font to see where it is at this point in time. Wish I could help out but I've not much experience with font development... 
I'll leave this open so that others wondering the same can see it

1.4 is still very much usable, so take the time you need :)

**Comment by dkraines** [comment]
Hey @jpt sorry to hear how awful your year has been. Just wanted to check in a see if you were able to touch base with google fonts? We really love this font and the vertical centering would be huge for us. Thank you for all you have done!

**Comment by jpt** [comment]
@dkraines I haven't. you can download [the 1.5 branch binaries](https://github.com/jpt/barlow/archive/refs/heads/1.5.zip) if vertical centering is an urgent matter for you, though I haven't done any QA on them
