### ISSUE TITLE
SemiCondensed ExtraLight - nameID 1 different in Roman and Italic

### ISSUE THREAD

**Issue by kenmcd** [jpt/barlow#97]
In the latest 1.500 build (2024-04-19) from here:
https://github.com/jpt/barlow/archive/refs/heads/1.5.zip

The SemiCondensed ExtraLight fonts have a different `nameID 1` in the Roman and the Italic.
This causes the style linking to not work properly.
The Italic button will not work properly on the Roman.
And the fonts are listed as two different families in the font menu.

Barlow SemiCondensed ExtraLight, and
Barlow SemiCondensed ExtraLight Italic
should have the same `nameID 1`.

**Comment by jpt** [comment]
Thanks for the report, I'll have a look at the name table

**Comment by jpt** [comment]
oh, maybe this is because the name is too long

**Comment by kenmcd** [comment]
Yes. One of them is 32 characters. 
It looks like they are both being shortened/abbreviated automatically, but differently.

**Comment by jpt** [comment]
[BarlowNameFix.zip](https://github.com/jpt/barlow/files/15084677/BarlowNameFix.zip)
does this fix it?

**Comment by kenmcd** [comment]
Looks good.

**Comment by jpt** [comment]
fixed in [2596aa7](https://github.com/jpt/barlow/commit/2596aa7b81618027170c7ba9272d3761a4a36323)

I haven't looked at what fontbakery has to say yet but I'm hoping I'm getting close to merging 1.5.
